de_mirage = {
    {
        name = "Stairs",
        position = Vector.new(815, -1271, -109),
        angle = QAngle.new(2, -165.4, 0),
        jump = true,
        throwdelay = 6,
        jumpdelay = 8,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(-37, -1557, -168),
        angle = QAngle.new(-39.21, 174.67, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 10,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Plant",
        position = Vector.new(-531, -1385, -120),
        angle = QAngle.new(-3.32, -74.41, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Plant",
        position = Vector.new(-532.2, -1387.6, -118.8),
        angle = QAngle.new(-0.86, -73.66, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    }
    ,
    {
        name = "Connector",
        position = Vector.new(-432.6, -1886.6, -177.9),
        angle = QAngle.new(-2.1, 113.74, 0),
        jump = false,
        throwdelay = 3,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Top Pit",
        position = Vector.new(-22, -1742, -168),
        angle = QAngle.new(-15.41, 66.85, 0),
        jump = true,
        throwdelay = 17,
        jumpdelay = 18,
        forward = 240,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Pit",
        position = Vector.new(-1269, -2463, -190),
        angle = QAngle.new(-18.02, 28.55, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 8,
        forward = 260,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Palace",
        position = Vector.new(-1178, -2285, -183),
        angle = QAngle.new(-23.56, 5.54, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Top Pit",
        position = Vector.new(-4, -1539, -169),
        angle = QAngle.new(41.7, -4, 0),
        jump = true,
        throwdelay = 64,
        jumpdelay = 33,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Oneway",
        position = Vector.new(1183, 300, -252.2),
        angle = QAngle.new(-15.19, 140, 0),
        jump = false,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Oneway",
        position = Vector.new(1183, 300, -252.2),
        angle = QAngle.new(-15.19, 140, 0),
        jump = false,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Fake Duck",
        position = Vector.new(932, 506, -254.3),
        angle = QAngle.new(-20.54, -56.89, 0),
        jump = false,
        throwdelay = 10,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(932, 506, -254.3),
        angle = QAngle.new(-20.54, -56.89, 0),
        jump = false,
        throwdelay = 10,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "T Spawn",
        position = Vector.new(951, -1183, -261),
        angle = QAngle.new(-19.96, 54.68, 0),
        jump = false,
        throwdelay = 10,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Top Pit",
        position = Vector.new(301, -735, -88),
        angle = QAngle.new(-12.27, -29.30, 0),
        jump = true,
        throwdelay = 0,
        jumpdelay = 1,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Fake Duck",
        position = Vector.new(372, -1711, -198.4),
        angle = QAngle.new(-16.64, 125.16, 0),
        jump = false,
        throwdelay = 14,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Fake Duck",
        position = Vector.new(372, -1711, -198.4),
        angle = QAngle.new(-16.64, 125.16, 0),
        jump = false,
        throwdelay = 9,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Right Connector",
        position = Vector.new(-880, -606, -262),
        angle = QAngle.new(-15.34, -50.5, 0),
        jump = false,
        throwdelay = 22,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Right Connector",
        position = Vector.new(-880, -606, -262),
        angle = QAngle.new(-15.34, -50.5, 0),
        jump = false,
        throwdelay = 22,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Chair",
        position = Vector.new(-720, -1018, -216),
        angle = QAngle.new(2, 73.5, 0),
        jump = true,
        throwdelay = 39,
        jumpdelay = 41,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Chair",
        position = Vector.new(-720, -1018, -216),
        angle = QAngle.new(2, 73.5, 0),
        jump = true,
        throwdelay = 27,
        jumpdelay = 31,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Plant",
        position = Vector.new(95.51, -2375, -40),
        angle = QAngle.new(16.54, 114.21, 0),
        jump = false,
        throwdelay = 3,
        jumpdelay = 0,
        forward = 230,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Plant",
        position = Vector.new(95.51, -2375, -40),
        angle = QAngle.new(11.85, 114.21, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Palace",
        position = Vector.new(182, -1718, -168),
        angle = QAngle.new(-7.64, 101.21, 0),
        jump = true,
        throwdelay = 29,
        jumpdelay = 32,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Palace",
        position = Vector.new(-690, -1268, -168),
        angle = QAngle.new(-21.88, -52, 0),
        jump = false,
        throwdelay = 27,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Palace",
        position = Vector.new(-690, -1268, -168),
        angle = QAngle.new(-21.88, -52, 0),
        jump = false,
        throwdelay = 27,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Tetris",
        position = Vector.new(-624.9, -1524.58, -168),
        angle = QAngle.new(-38.36, 0, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(473, 410, -252),
        angle = QAngle.new(-36.8, 180, 0),
        jump = true,
        throwdelay = 4,
        jumpdelay = 6,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(-1073, -1397, -169.4),
        angle = QAngle.new(5.9, 121.77, 0),
        jump = false,
        throwdelay = 24,
        jumpdelay = 6,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(-1073, -1397, -169.4),
        angle = QAngle.new(5.9, 121.77, 0),
        jump = false,
        throwdelay = 24,
        jumpdelay = 6,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Jungle",
        position = Vector.new(-1608, -1429, -265.6),
        angle = QAngle.new(-10.47, 65.9, 0),
        jump = false,
        throwdelay = 24,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Window",
        position = Vector.new(-1070.36, -61.80, -168),
        angle = QAngle.new(-16.95, -117.17, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(120, -893.8, -40),
        angle = QAngle.new(3.8, -158.24, 0),
        jump = true,
        throwdelay = 25,
        jumpdelay = 24,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(120, -893.8, -40),
        angle = QAngle.new(3.8, -158.24, 0),
        jump = true,
        throwdelay = 25,
        jumpdelay = 24,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(656, -1128, -128),
        angle = QAngle.new(-4.6, -135.4, 0),
        jump = true,
        throwdelay = 8,
        jumpdelay = 1,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Pit",
        position = Vector.new(-1120, -1527, -156),
        angle = QAngle.new(-10.11, 0, 0),
        jump = false,
        throwdelay = 20,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(-58, -1550.45, -168),
        angle = QAngle.new(-46.37, 163.65, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Stairs",
        position = Vector.new(665, -1665.45, -258.5),
        angle = QAngle.new(-25.20, 170.38, 0),
        jump = false,
        throwdelay = 25,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Stairs",
        position = Vector.new(665, -1665.45, -258.5),
        angle = QAngle.new(-25.20, 170.38, 0),
        jump = false,
        throwdelay = 25,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Stairs",
        position = Vector.new(1004, -1212, -109),
        angle = QAngle.new(-20.2, -164.9, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Rip ESP",
        position = Vector.new(-473, -1601, -40),
        angle = QAngle.new(0, 102.79, 0),
        jump = true,
        throwdelay = 16,
        jumpdelay = 8,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Top Pit",
        position = Vector.new(-55, -1986, -40),
        angle = QAngle.new(2.30, 72, 0),
        jump = true,
        throwdelay = 33,
        jumpdelay = 32,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Appartments",
        position = Vector.new(-1042, 282, -368),
        angle = QAngle.new(-34.59, 47.69, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Short",
        position = Vector.new(-1048, 125, -360),
        angle = QAngle.new(-70.7, -179.66, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Appartments",
        position = Vector.new(-2063, 445, -160),
        angle = QAngle.new(-16.7, 26.16, 0),
        jump = false,
        throwdelay = 32,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Kitchen",
        position = Vector.new(-1802, 737, -48),
        angle = QAngle.new(-3.71, -96.8, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Palace",
        position = Vector.new(596.7, -2325.4, -40),
        angle = QAngle.new(-7.4, -174.1, 0),
        jump = false,
        throwdelay = 64,
        jumpdelay = 63,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Palace",
        position = Vector.new(596.7, -2325.4, -40),
        angle = QAngle.new(-7.4, -174.1, 0),
        jump = false,
        throwdelay = 64,
        jumpdelay = 63,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Plant",
        position = Vector.new(-2155.3, -617.3, -168),
        angle = QAngle.new(-13.11, 51.78, 0),
        jump = false,
        throwdelay = 20,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(1196, -1480, -168),
        angle = QAngle.new(-3.25, 51.75, 0),
        jump = false,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Palace",
        position = Vector.new(576.6, -1471.9, -258),
        angle = QAngle.new(-24.9, 45, 0),
        jump = false,
        throwdelay = 8,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Short",
        position = Vector.new(-1048, -240.5, -368),
        angle = QAngle.new(-7.16, -74.46, 0),
        jump = false,
        throwdelay = 15,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Oneway",
        position = Vector.new(-460, 887.9, -72),
        angle = QAngle.new(-0.64, -25.47, 0),
        jump = true,
        throwdelay = 10,
        jumpdelay = 9,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Oneway",
        position = Vector.new(-460, 887.9, -72),
        angle = QAngle.new(-0.64, -25.47, 0),
        jump = true,
        throwdelay = 10,
        jumpdelay = 9,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(53.1, 825.8, -136),
        angle = QAngle.new(-13.34, -161.07, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(53.1, 825.8, -136),
        angle = QAngle.new(-13.34, -161.07, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = HE
    },
    {
        name = "Oneway",
        position = Vector.new(-11, 772.8, -136),
        angle = QAngle.new(-26.81, -174.77, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Mid",
        position = Vector.new(-573.2, 407.2, -211.4),
        angle = QAngle.new(-44.5, -0.19, 0),
        jump = true,
        throwdelay = 64,
        jumpdelay = 63,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Oneway",
        position = Vector.new(811.8, 518.1, -259.4),
        angle = QAngle.new(-22.96, 138, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Oneway",
        position = Vector.new(811.8, 518.1, -259.4),
        angle = QAngle.new(-22.96, 138, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = HE
    },
    {
        name = "Mid",
        position = Vector.new(810.4, -1373.9, -109),
        angle = QAngle.new(-15.49, 105.05, 0),
        jump = true,
        throwdelay = 40,
        jumpdelay = 32,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Top Pit",
        position = Vector.new(192.7, -294.1, -170.3),
        angle = QAngle.new(-15.8, -50.62, 0),
        jump = true,
        throwdelay = 33,
        jumpdelay = 27,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Top Pit",
        position = Vector.new(-505.1, -1573.7, -40),
        angle = QAngle.new(11.5, 3, 0),
        jump = true,
        throwdelay = 28,
        jumpdelay = 29,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Underground",
        position = Vector.new(-1200, -155.2, -53.9),
        angle = QAngle.new(15.15, -73.15, 0),
        jump = false,
        throwdelay = 18,
        jumpdelay = 0,
        forward = 450,
        side = 450,
        type = HE
    },
    {
        name = "Underground",
        position = Vector.new(-1200, -155.2, -53.9),
        angle = QAngle.new(15.15, -73.15, 0),
        jump = false,
        throwdelay = 18,
        jumpdelay = 0,
        forward = 450,
        side = 450,
        type = MOLOTOV
    },
    {
        name = "Ladder",
        position = Vector.new(-980.5, -274.2, -368),
        angle = QAngle.new(-45.21, -105.21, 0),
        jump = false,
        throwdelay = 25,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Ladder",
        position = Vector.new(-980.5, -274.2, -368),
        angle = QAngle.new(-45.21, -105.21, 0),
        jump = false,
        throwdelay = 25,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Stairs",
        position = Vector.new(-91.1, -1418.1, -116),
        angle = QAngle.new(-9.3, -63.55, 0),
        jump = true,
        throwdelay = 9,
        jumpdelay = 8,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Short",
        position = Vector.new(-2325.3, 812.5, -119.7),
        angle = QAngle.new(-5.86, -25.45, 0),
        jump = false,
        throwdelay = 15,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Column",
        position = Vector.new(-2155, 830.7, -125.7),
        angle = QAngle.new(-9.3, -26.07, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(384, 273.7, -256.6),
        angle = QAngle.new(-10, -113.28, 0),
        jump = false,
        throwdelay = 8,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Plant",
        position = Vector.new(-757, -31.1, -162.4),
        angle = QAngle.new(5.61, 145.66, 0),
        jump = true,
        throwdelay = 6,
        jumpdelay = 3,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Kitchen",
        position = Vector.new(-1513.1, -1515.6, -260),
        angle = QAngle.new(-15.11, 142.3, 0),
        jump = true,
        throwdelay = 28,
        jumpdelay = 29,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Tetris",
        position = Vector.new(-661, -1521, -168),
        angle = QAngle.new(-42.89, 0.58, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Stairs",
        position = Vector.new(-970.8, 285.3, -167.9),
        angle = QAngle.new(-2.5, -73.49, 0),
        jump = true,
        throwdelay = 29,
        jumpdelay = 30,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(-918.7, -380.1, -48.1),
        angle = QAngle.new(-19.2, -146.74, 0),
        jump = true,
        throwdelay = 19,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Top Pit",
        position = Vector.new(195.1, -210.8, -169.6),
        angle = QAngle.new(-6, -54.39, 0),
        jump = true,
        throwdelay = 28,
        jumpdelay = 29,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "FPS Abuser",
        position = Vector.new(-760.7, -1633.7, -169),
        angle = QAngle.new(-0.17, -87.61, 0),
        jump = true,
        throwdelay = 38,
        jumpdelay = 33,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Palace",
        position = Vector.new(256.1, -711.2, -88),
        angle = QAngle.new(-11, -28.08, 0),
        jump = true,
        throwdelay = 14,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Chair",
        position = Vector.new(-1062.1, 277.6, -167.3),
        angle = QAngle.new(-15.73, -55.9, 0),
        jump = false,
        throwdelay = 1,
        jumpdelay = 0,
        forward = 180,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Connector",
        position = Vector.new(-932.7, 219.6, -172.8),
        angle = QAngle.new(0.68, -77.7, 0),
        jump = true,
        throwdelay = 13,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Mid",
        position = Vector.new(-2088.7, 663.6, -44),
        angle = QAngle.new(-6.56, -19.57, 0),
        jump = true,
        throwdelay = 27,
        jumpdelay = 28,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Pit Corner",
        position = Vector.new(875.9, -1213, -109),
        angle = QAngle.new(-4, -163.9, 0),
        jump = true,
        throwdelay = 33,
        jumpdelay = 25,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "CT",
        position = Vector.new(-78, -1993.4, -168),
        angle = QAngle.new(-2.24, -157.67, 0),
        jump = true,
        throwdelay = 14,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Oneway",
        position = Vector.new(-1021.2, -2365.6, -168),
        angle = QAngle.new(-21.2, 136.85, 0),
        jump = true,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Ticket",
        position = Vector.new(-880, -1306.1, -168),
        angle = QAngle.new(-7.79, -88.45, 0),
        jump = true,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Fake Duck",
        position = Vector.new(-309.9, -1724.2, -168),
        angle = QAngle.new(1.75, 129.91, 0),
        jump = true,
        throwdelay = 13,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = HE
    },
    {
        name = "Fake Duck",
        position = Vector.new(-309.9, -1724.2, -168),
        angle = QAngle.new(1.75, 129.91, 0),
        jump = true,
        throwdelay = 13,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Tetris",
        position = Vector.new(-1110, -2444.2, -168),
        angle = QAngle.new(-22, 41.3, 0),
        jump = true,
        throwdelay = 17,
        jumpdelay = 2,
        forward = 120,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Top Pit",
        position = Vector.new(-454.3, -1627.7, -40),
        angle = QAngle.new(-18, 16.7, 0),
        jump = false,
        throwdelay = 4,
        jumpdelay = 0,
        forward = 250,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "B Apps",
        position = Vector.new(-478.7, -2367.4, -168),
        angle = QAngle.new(-27, 113.5, 0),
        jump = true,
        throwdelay = 30,
        jumpdelay = 30,
        forward = 450,
        side = 0,
        type = SMOKE
    },
    {
        name = "B Plant",
        position = Vector.new(-304.3, -2018.2, -172.4),
        angle = QAngle.new(-18.61, 120.3, 0),
        jump = true,
        throwdelay = 32,
        jumpdelay = 32,
        forward = 450,
        side = 0,
        type = SMOKE
    },
    {
        name = "СT",
        position = Vector.new(762.7, -1201.6, -109),
        angle = QAngle.new(-1.71, -145.4, 0),
        jump = true,
        throwdelay = 2,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = SMOKE
    },
    {
        name = "Stairs",
        position = Vector.new(1148.5, -1184, -205.7),
        angle = QAngle.new(-42.98, -165.17, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = SMOKE
    }
}
de_overpass = {
    {
        name = "Water",
        position = Vector.new(-1108.2, -639, 93),
        angle = QAngle.new(-2.7, 89.9, 0),
        jump = true,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Water",
        position = Vector.new(-1108.2, -639, 93),
        angle = QAngle.new(-2.7, 89.9, 0),
        jump = true,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 0,
        side = 0.0,
        type = HE
    },
    {
        name = "Barrels",
        position = Vector.new(-1583, -731, 136),
        angle = QAngle.new(4.85, 58.34, 0),
        jump = true,
        throwdelay = 1,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Corner",
        position = Vector.new(-1410.2, -725.7, 21.2),
        angle = QAngle.new(-20.09, 68.36, 0),
        jump = true,
        throwdelay = 80,
        jumpdelay = 46,
        forward = 140,
        side = 450,
        type = MOLOTOV
    },
    {
        name = "Corner",
        position = Vector.new(-1409.8, -964.1, 15.3),
        angle = QAngle.new(-17.27, 51.7, 0),
        jump = false,
        throwdelay = 2,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = HE
    },
    {
        name = "Plant",
        position = Vector.new(-1364.6, -859, 15.4),
        angle = QAngle.new(-24.49, 47.46, 0),
        jump = false,
        throwdelay = 20,
        jumpdelay = 0,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Plant",
        position = Vector.new(-1228.6, -597.7, 48),
        angle = QAngle.new(-13.3, 154.4, 0),
        jump = true,
        throwdelay = 41,
        jumpdelay = 42,
        forward = 450,
        side = 0.0,
        type = MOLOTOV
    },
    {
        name = "Short",
        position = Vector.new(-1963.7, 11.4, 128),
        angle = QAngle.new(-12.18, -22.63, 0),
        jump = false,
        throwdelay = 15,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Heaven",
        position = Vector.new(-1251.4, -1064.4, 0),
        angle = QAngle.new(-3.6, 107.4, 0),
        jump = true,
        throwdelay = 26,
        jumpdelay = 25,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Heaven",
        position = Vector.new(-1251.4, -1064.4, 0),
        angle = QAngle.new(-3.6, 107.4, 0),
        jump = true,
        throwdelay = 26,
        jumpdelay = 25,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Barrels",
        position = Vector.new(-582, -1289.6, 136),
        angle = QAngle.new(-1, 100, 0),
        jump = true,
        throwdelay = 52,
        jumpdelay = 49,
        forward = 450,
        side = 0,
        type = HE
    },
    {
        name = "Barrels",
        position = Vector.new(-582, -1289.6, 136),
        angle = QAngle.new(-1, 100, 0),
        jump = true,
        throwdelay = 52,
        jumpdelay = 49,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Water",
        position = Vector.new(-547, -1282.1, 133),
        angle = QAngle.new(-0.1, 109.3, 0),
        jump = true,
        throwdelay = 52,
        jumpdelay = 49,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Water",
        position = Vector.new(-1420.8, -797.8, 28.9),
        angle = QAngle.new(-16.7, 87.63, 0),
        jump = true,
        throwdelay = 100,
        jumpdelay = 50,
        forward = 10,
        side = 450,
        type = MOLOTOV
    },
    {
        name = "Barrels",
        position = Vector.new(-1439.9, -839.7, 32.5),
        angle = QAngle.new(-17.9, 77.4, 0),
        jump = true,
        throwdelay = 90,
        jumpdelay = 50,
        forward = 130,
        side = 450,
        type = MOLOTOV
    },
    {
        name = "Water",
        position = Vector.new(-1439.9, -839.7, 32.5),
        angle = QAngle.new(-17.9, 84.4, 0),
        jump = true,
        throwdelay = 90,
        jumpdelay = 50,
        forward = 70,
        side = 450,
        type = HE
    },
    {
        name = "Heaven",
        position = Vector.new(-1125.1, -639, 84.5),
        angle = QAngle.new(-11.2, 117.58, 0),
        jump = true,
        throwdelay = 7,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Bricks",
        position = Vector.new(-218.5, -875.7, 43),
        angle = QAngle.new(0.3, 162, 0),
        jump = true,
        throwdelay = 30,
        jumpdelay = 31,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Barrels",
        position = Vector.new(-1585, -943.4, 136),
        angle = QAngle.new(-12.4, 61.27, 0),
        jump = false,
        throwdelay = 2,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Column",
        position = Vector.new(-1582.2, -834.5, 136),
        angle = QAngle.new(-11.79, 58.55, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Plant Box",
        position = Vector.new(-1269.5, -629, 37.2),
        angle = QAngle.new(-11.48, 150.25, 0),
        jump = true,
        throwdelay = 28,
        jumpdelay = 29,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Backplant",
        position = Vector.new(-569.6, -88.4, 1.7),
        angle = QAngle.new(-12.33, 169.46, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Brick",
        position = Vector.new(-2230, 867.2, 256),
        angle = QAngle.new(-1.16, -33.85, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Barrels",
        position = Vector.new(-457.5, 373.9, 16.8),
        angle = QAngle.new(-26.49, -148.96, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Barrels",
        position = Vector.new(-457.5, 373.9, 16.8),
        angle = QAngle.new(-26.49, -148.96, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = HE
    },
    {
        name = "Short",
        position = Vector.new(-1233.1, -289.2, 100.7),
        angle = QAngle.new(-4.48, 46.77, 0),
        jump = true,
        throwdelay = 14,
        jumpdelay = 15,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Corner",
        position = Vector.new(-856.1, -556.6, 96),
        angle = QAngle.new(-34.27, 93.36, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Barrels",
        position = Vector.new(-866.6, -586, 96),
        angle = QAngle.new(-9.71, 88.04, 0),
        jump = false,
        throwdelay = 0,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Backplant",
        position = Vector.new(-769.2, 45, 72.5),
        angle = QAngle.new(-13.11, 126.16, 0),
        jump = false,
        throwdelay = 6,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Connector",
        position = Vector.new(-3746.1, -769.6, 492.4),
        angle = QAngle.new(-16.87, -21.21, 0),
        jump = true,
        throwdelay = 21,
        jumpdelay = 5,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Palyground",
        position = Vector.new(-2352, -693.2, 429.9),
        angle = QAngle.new(-8.5, -83, 0),
        jump = true,
        throwdelay = 33,
        jumpdelay = 26,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "B Plant",
        position = Vector.new(-3773.8, -2037.1, 493.1),
        angle = QAngle.new(-2.66, 38.13, 0),
        jump = true,
        throwdelay = 68,
        jumpdelay = 69,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Toilets",
        position = Vector.new(-3128.5, -2365.3, 474.2),
        angle = QAngle.new(1.07, 71, 0),
        jump = true,
        throwdelay = 4,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Toilets",
        position = Vector.new(-1855.6, -2435.2, 415.5),
        angle = QAngle.new(-5, 119.19, 0),
        jump = true,
        throwdelay = 49,
        jumpdelay = 41,
        forward = 450,
        side = 0,
        type = MOLOTOV
    }
    
}
de_cobblestone = {
    {
        name = "Under Tree",
        position = Vector.new(-356.7, -154.7, -32),
        angle = QAngle.new(-56.14, -50.29, 0),
        jump = true,
        throwdelay = 1,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Plant Corner",
        position = Vector.new(73.4, -139.7, -29.9),
        angle = QAngle.new(3, -13.55, 0),
        jump = false,
        throwdelay = 20,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "T Alley",
        position = Vector.new(-251.7, -624.6, -64),
        angle = QAngle.new(-2.2, 30.87, 0),
        jump = false,
        throwdelay = 12,
        jumpdelay = 0,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "T Alley",
        position = Vector.new(-167.3, -466.1, -32),
        angle = QAngle.new(-61, 109.89, 0),
        jump = true,
        throwdelay = 0,
        jumpdelay = 1,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Under Tree",
        position = Vector.new(124.8, -80.1, -25.6),
        angle = QAngle.new(-39, -133.5, 0),
        jump = true,
        throwdelay = 12,
        jumpdelay = 13,
        forward = 450,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Under Tree",
        position = Vector.new(-304, -16.1, -32),
        angle = QAngle.new(-13.2, -33.5, 0),
        jump = true,
        throwdelay = 9,
        jumpdelay = 0,
        forward = 0,
        side = 0,
        type = MOLOTOV
    },
    {
        name = "Under Tree",
        position = Vector.new(-100, -139.7, -32),
        angle = QAngle.new(-43.79, -110.94, 0),
        jump = true,
        throwdelay = 0,
        jumpdelay = 1,
        forward = 0,
        side = 0,
        type = HE
    },
    {
        name = "Stone",
        position = Vector.new(-55.1, -16.4, -32),
        angle = QAngle.new(-45.09, -111.04, 0),
        jump = true,
        throwdelay = 13,
        jumpdelay = 12,
        forward = 450,
        side = 0,
        type = MOLOTOV
    }
}